# Dependencies



# Permalinks
permalink:        pretty

# Setup
title:            hocuspocus
tagline:          'Library for working with a CTS archive'
description:      'hocuspocus is a library for working with a CTS archive'
baseurl: '/hocuspocus/'


author:
  name:           'Neel Smith'


paginate:         5

github:
  repo:           https://github.com/neelsmith/hocuspocus


links:
  - title: Documentation
    url: /docs
  - title: Live specification
    url: /specs/hocuspocus/Hocuspocus.html
  - title: API docs
    url: /api
  - title: Github project
    url: https://github.com/cite-architecture/hocuspocus
    external: true
  - title: CITE architecture home page
    url: http://cite-architecture.github.io/
    external: true
